sonar.projectKey=GabrielMainiere_js-api-cicd
sonar.projectName=js-api-cicd
sonar.organization=gabrielmainiere
sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.exclusions=node_modules/**,tests/**

sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.js
